routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\PlayerController;
use App\Models\Team;
use App\Models\Player;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resources([
    'team' => TeamController::class,
    'player' => PlayerController::class
]);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/players',function(){
    return view('players');
});

Route::group(['middleware' => ['auth']], function () {
    //! Rutas del administrador
    Route::get('/admin',function(){return view('admin.index');})->name('admin');

    Route::get('/team/{id}/delete', [TeamController::class ,'delete'])->name('team.delete');
    Route::get('/player/{id}/delete', [PlayerController::class ,'delete'])->name('player.delete');
});

//! Variables globales
View::composer('index', function ($view) {
    $teams = DB::table('teams')->orderBy('win','desc')->get();
    $view->with('teams', $teams);
});
View::composer('players', function ($view) {
    $players = Player::all();
    $view->with('players', $players);
});

resources/views/admin/index.blade.php
@extends('layouts.guest')
@section('content')
<div class="container">
    <div id="div-admin-buttons" class="row mt-3 justify-content-center">
        <div class="col-6 col-md-3">
            <a href="{{route('player.index')}}">
                <button class="btn col-12 btn-outline-dark rounded-pill">PLAYERS NEFASTOS</button>
            </a>
        </div>
        <div class="col-6 col-md-3">
            <a href="{{route('team.index')}}">
                <button class="btn col-12 btn-outline-dark rounded-pill">TEAMS</button>
            </a>
        </div>
    </div>
</div>
@endsection