routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\PlayerController;
use App\Models\Team;
use App\Models\Player;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resources([
    'team' => TeamController::class,
    'player' => PlayerController::class
]);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/players',function(){
    return view('players');
});

Route::group(['middleware' => ['auth']], function () {
    //! Rutas del administrador
    Route::get('/admin',function(){return view('admin.index');})->name('admin');

    Route::get('/team/{id}/delete', [TeamController::class ,'delete'])->name('team.delete');
    Route::get('/player/{id}/delete', [PlayerController::class ,'delete'])->name('player.delete');
});

//! Variables globales
View::composer('index', function ($view) {
    $teams = DB::table('teams')->orderBy('win','desc')->get();
    $view->with('teams', $teams);
});
View::composer('players', function ($view) {
    $players = Player::all();
    $view->with('players', $players);
});

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function players()
    {
        return $this->hasMany(Player::class, 'team_id');
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\Team;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teams = Team::all();
        $vac = compact('teams');
        return view('admin.team.index',$vac);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request);
        $games_played = $request['win'] + $request['lose'];
        Team::create([
            'name' => $request->input('name'),
            'tag' => $request->input('tag'),
            'games_played' => $games_played,
            'win' => $request->input('win'),
            'lose' => $request->input('lose'),
            'kills' => 0,
            'deaths' => 0
        ]);

        return redirect()->route('team.index')->with('notice', 'El equipo '.ucfirst($request['name']).' se agrego ANAAAAAANAAANASHEEEEEEE');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $team = Team::find($id);
        $vac = compact('team');
        return view('team.show',$vac);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $team = Team::find($id);
        $vac = compact('team');
        return view('admin.team.edit',$vac);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $team = Team::find($id);
        $games_played = $request['win'] + $request['lose'];
        $team->update([
            'name' => $request['name'],
            'tag' => $request['tag'],
            'games_played' => $games_played,
            'win' => $request['win'],
            'lose' => $request['lose'],
            'kills' => $request['kills'],
            'deaths' => $request['deaths']
        ]);
        return redirect()->route('team.index')->with('notice', 'El equipo '.ucfirst($team->name).' se edito de una.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\
     */
    
    public function delete($id)
    {
        $team = Team::find($id);
        $team->delete();
        return redirect()->route('team.index')->with('notice', 'El equipo '.Ucfirst($team->name).' se fue DELETEATRES BROOO');
    }
    
    public function validator(Request $request)
    {
        $rules = [
            'name' => 'required|unique:teams|string|max:50',
            'tag' => 'required|unique:teams|string|max:4',
            'win' => 'required|integer',
            'lose' => 'required|integer',
        ];
        $message = [
            'required' => 'El campo es obligatorio.',
            'unique' => 'El equipo ya existe.',
            'string' => 'Solo se admiten letras.',
            'integer' => 'Solo se admiten numeros.',
        ];
        return $this->validate($request, $rules, $message);
    }
}

resources/views/admin/team/create.blade.php
@extends('layouts.guest')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Nuevo Team</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('team.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-row justify-content-center">
            <div class="form-group col-12 col-md-6 col-lg-2">
                <h4><label for="">Nombre</label></h4>
                <input name="name" class="form-control" type="text" value="{{ old('name') }}">
                <small class="form-text text-muted"><b>Nombre del nuevo equipo</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">Tag</label></h4>
                <input name="tag" class="form-control" type="text" value="{{ old('tag') }}">
                <small class="form-text text-muted"><b>Tag del equipo</b></small>
                @error('tag')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">PG</label></h4>
                <input name="win" class="form-control" type="number" value="{{ old('win') }}">
                <small class="form-text text-muted"><b>Partidos ganados</b></small>
                @error('win')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">PP</label></h4>
                <input name="lose" class="form-control" type="number" value="{{ old('lose') }}">
                <small class="form-text text-muted"><b>Partidos perdidos</b></small>
                @error('lose')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
        <div id="buttons" class="text-center mt-3 col-12">
            <button class="mx-2 btn btn-outline-dark rounded-pill" type="submit">Agregar</button>
            <a href="{{route('team.index')}}"><button class="btn btn-outline-dark rounded-pill" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/team/edit.blade.php
@extends('layouts.guest')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Editar Team</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('team.update',['team'=>$team])}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-row justify-content-center">
            <div class="form-group col-12 col-md-6 col-lg-2">
                <label class="h4 pb-2" for="">Nombre</label>
                <input name="name" class="form-control" type="text" value="{{ $team->name }}">
                <small class="form-text text-muted"><b>Nuevo nombre del equipo</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">Tag</label></h4>
                <input name="tag" class="form-control" type="text" value="{{ $team->tag }}">
                <small class="form-text text-muted"><b>Tag del equipo</b></small>
                @error('tag')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">PG</label></h4>
                <input name="win" class="form-control" type="number" value="{{ $team->win}}">
                <small class="form-text text-muted"><b>Partidos ganados</b></small>
                @error('win')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">PP</label></h4>
                <input name="lose" class="form-control" type="number" value="{{ $team->lose }}">
                <small class="form-text text-muted"><b>Partidos perdidos</b></small>
                @error('lose')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">Kills</label></h4>
                <input name="kills" class="form-control" type="number" value="{{ $team->kills }}">
                <small class="form-text text-muted"><b>Kills</b></small>
                @error('kills')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div class="form-group col-12 col-md-6 col-lg-1">
                <h4 class="text-center"><label for="">Deaths</label></h4>
                <input name="deaths" class="form-control" type="number" value="{{ $team->deaths }}">
                <small class="form-text text-muted"><b>Deaths</b></small>
                @error('deaths')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="buttons" class="text-center mt-3 col-12">
                <button class="mx-2 btn btn-outline-dark rounded-pill" type="submit">Editar</button>
                <a href="{{route('team.index')}}"><button class="btn btn-outline-dark rounded-pill" type="button">Cancelar</button></a>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/admin/team/index.blade.php
@extends('layouts.guest')
@section('content')
<div class="container">
    <div class="col-12">
        <div class="mx-auto text-center col-12">
            <h2>Teams</h2>
            <a href="{{route('admin')}}" style="text-decoration: none; color:black"><i class="fas fa-arrow-circle-left"></i> Volver</a>
        </div>
        <div class="row justify-content-center mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
            <div class="my-3 col-6 col-md-4">
                <a href="{{route('team.create')}}"><button class="btn btn-outline-dark rounded-pill w-100">Nuevo</button></a>
            </div>
        </div>
        <div class="my-2 col-12 text-center">
            @if(Session::has('notice'))
            <h3 class="my-auto text-success"><strong>{{ Session::get('notice') }}</strong></h3>
            @endif
        </div>
    </div>
    <div class="table table-hover" style="overflow-x:auto;">
        <table class="mx-auto">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Tag</th>
                    <th scope="col">PJ</th>
                    <th scope="col">PG</th>
                    <th scope="col">PP</th>
                    <th scope="col">Kills</th>
                    <th scope="col">Deaths</th>
                    <th scope="col" colspan="2">Opciones</th>
                </tr>
            </thead>
            <tbody>
                @if (isset($teams))
                    @foreach ($teams as $team)
                    <tr>
                        <th>{{$team->id}}</th>
                        <th>{{Ucfirst($team->name)}}</th>
                        <th>{{strtoupper($team->tag)}}</th>
                        <th>{{$team->games_played}}</th>
                        <th>{{$team->win}}</th>
                        <th>{{$team->lose}}</th>
                        <th>{{$team->kills}}</th>
                        <th>{{$team->deaths}}</th>
                        <th><a href="{{ route('team.edit',['team'=>$team])}}"><span class="material-icons" title="Editar">edit</span></a></th>
                        <th><a href="{{ route('team.delete',['id'=>$team->id])}}"><span class="material-icons" title="Eliminar">delete_outline</span></a></th>
                    </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
</div>
@endsection